name: 3. Multiple Steps Action

on:
  push:
    branches:
      - main

jobs:
  step-by-step:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 단계
        run: echo "준비 중입니다..."
      
      - name: 두 번째 단계
        run: echo "작업을 실행합니다."
        
      - name: 세 번째 단계
        run: echo "모든 작업이 완료되었습니다!"
